name: Tex Build Test
on: [push, pull_request]

jobs:
  ubuntu-build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Test Doc Compilation
        uses: xu-cheng/latex-action@v2
        with:
          root_file: "hfutthesis-doc.tex"
          latexmk_use_xelatex: true
          latexmk_shell_escape: true
          args: "-outdir=ci_out/ubuntu/hfutthesis-doc"
      - name: Test Main Compilation
        uses: xu-cheng/latex-action@v2
        with:
          root_file: "main.tex"
          latexmk_use_xelatex: true
          latexmk_shell_escape: true
          args: "-outdir=ci_out/ubuntu/main"
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ci_out
          path: ci_out
  post-ci-output-dev:
    runs-on: ubuntu-latest
    if: github.repository == 'HFUTTUG/HFUT_Thesis' && github.event_name == 'push'
    needs: [ubuntu-build-test]
    steps:
      - name: Upload Artifact
        uses: actions/download-artifact@v2
        with:
          name: ci_out
          path: ci_out
      - name: Release to External Repo
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.CI_DEPLOY }}
          external_repository: HFUTTUG/CI_Output
          publish_branch: HFUTTUG/HFUT_Thesis
          publish_dir: ci_out
          force_orphan: false
